### ISSUE TITLE
v1.0 Road map

### ISSUE THREAD

**Issue by duongdev** [duongdev/golb#1]
# Core features

- [x] Guests can read all the posts.
- [x] Authenticate with email/password or social account.
- [x] Authenticated users can create new posts and update/remove their own posts.
- [x] Authenticated users can comment on any post.
- [x] Posts can be searched/filtered.
- [x] Deploy to Vercel and Heroku.
